name: Bug report
description: Report a problem
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and steps to reproduce
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Plugin version
  - type: input
    id: wp
    attributes:
      label: WordPress version
  - type: input
    id: php
    attributes:
      label: PHP version
