name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: What would you like?
    validations:
      required: true
