name: CI

on:
  pull_request:
    branches: [main]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install
        run: composer install --no-interaction --prefer-dist
      - name: Guard: no WP functions in tests
        run: |
          if rg -n -P '^[ \t]*function (?!fbm_)' tests | grep -v 'tests/Support/WPStubs.php'; then
            echo 'WP function declarations found in tests';
            exit 1;
          fi
      - name: PHPCS lanes
        run: composer phpcs:lanes
      - name: QA
        env:
          FBM_PHPSTAN: 1
        run: composer qa
