name: CI

on:
  pull_request:
    branches: [main]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install
        run: composer install --no-interaction --prefer-dist
      - name: PHPCS lane
        run: |
          vendor/bin/phpcs --standard=phpcs.xml --report=summary \
            includes/Http/FormSubmitController.php \
            includes/Database/ApplicationsRepo.php \
            includes/Mail/LogRepo.php \
            includes/Shortcodes/Shortcodes.php \
            includes/Shortcodes/FormShortcode.php \
            includes/Shortcodes/DashboardShortcode.php \
            includes/Core/Assets.php \
            includes/Admin/DiagnosticsPage.php \
            templates/public/form-success.php \
            templates/public/dashboard.php
      - name: QA
        run: composer qa
