name: Build & Upload Release ZIP

on:
  release:
    types: [published]

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install deps
        run: composer install --no-interaction --prefer-dist
      - name: QA
        run: |
          composer phpcs
          composer phpstan:fast -- --memory-limit=1G
          composer phpstan
      - name: Package
        run: bash bin/package.sh
      - name: Upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/foodbank-manager.zip
